name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build --if-present
      - run: xvfb-run --auto-servernum npm test -- --no-watch
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
